# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches:
      - Main
      - Dev
      - Release
  pull_request:
    branches:
      - Main
      - Dev
      - Release

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Realizamos Checkout
      uses: actions/checkout@v2

    - name: Preparar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Instalar dependencias
      run: |
        cd AdoptaunProfe
        npm install
        npm install --save-dev jest

    - name: Ejecutar Tests
      run: |
        cd AdoptaunProfe
        if ! npm test; then
          echo "Uno o varios test han fallado. Se cancela el push."
          exit 1
        fi

    - name: Push changes
      if: success()
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}