# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - Main
      - Dev
      - Release

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      myapp:
        ports:
          - 80:80

    steps:
    - name: Realizamos Checkout
      uses: actions/checkout@v2

    - name: Preparar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Instalar dependencias
      run: |
        cd AdoptaunProfe
        npm install
        npm install --save-dev jest

    - name: Iniciar ngrok y capturar la URL
      id: ngrok
      run: |
        ./ngrok http 80 > ngrok_output.txt &
        sleep 10 # Espera un momento para que ngrok esté listo

    - name: Extraer URL de ngrok y almacenarla en un archivo
      run: |
        ngrok_url=$(grep -oE 'http://[a-z0-9]+\.ngrok\.io' ngrok_output.txt)
        echo "NGROK_URL=$ngrok_url" >> $GITHUB_ENV

    - name: Ejecutar Tests
      run: |
        cd AdoptaunProfe
        if ! npm test; then
          echo "Uno o varios test han fallado. Se cancela el push."
          exit 1
        fi